#!/bin/bash

clear

function sanitize_input() {
      if [ $1 -eq $1 2>/dev/null ] && [ $1 -gt 0 ] && [ $1 -lt 4 ]
      then
            return 0
      else
            return 1
      fi
}

echo "Select a technology to test with"
echo "1. Java"
echo "2. Python"
echo "3. C++"
read technology
sanitize_input $technology

while [ $? -eq 1 ]
do
      echo "Please enter a number between 1 and 3"
      read technology
      sanitize_input $technology
done

echo "Select the size of graph to use for the tests"
echo "1. Small (100 nodes)"
echo "2. Medium (1,000 nodes)"
echo "3. Large (10,000 nodes)"
read graph
sanitize_input $graph

while [ $? -eq 1 ]
do
      echo "Please enter a number between 1 and 3"
      read graph
      sanitize_input $graph
done

case $technology$graph in
      11)
            echo "Starting Java and small graph"
            cd Java
            javac -cp ".:jgrapht.jar" small_graph.java utils.java
            java -cp ".:jgrapht.jar" small_graph utils
            cd ..
            echo "Loading the graph with paths"
            python3 draw_graph/draw_small_graph.py
            ;;
      12)
            echo "Starting Java and Medium graph"
            cd Java
            javac -cp ".:jgrapht.jar" medium_graph.java utils.java
            java -cp ".:jgrapht.jar" medium_graph utils
            cd ..
            echo "Loading the graph with paths"
            python3 draw_graph/draw_medium_graph.py
            ;;
      13)
            echo "Starting Java and Large graph"
            cd Java
            javac -cp ".:jgrapht.jar" large_graph.java utils.java
            java -cp ".:jgrapht.jar" large_graph utils
            cd ..
            echo "Loading the graph with paths"
            python3 draw_graph/draw_large_graph.py
            ;;
      21)
            echo "Starting Python and small graph"
            python3 Python/small_graph.py
            echo "Loading the graph with paths"
            python3 draw_graph/draw_small_graph.py
            ;;
      22)
            echo "Starting Python and Medium graph"
            python3 Python/medium_graph.py
            echo "Loading the graph with paths"
            python3 draw_graph/draw_medium_graph.py
            ;;
      23)
            echo "Starting Python and Large graph"
            python3 Python/large_graph.py
            echo "Loading the graph with paths"
            python3 draw_graph/draw_large_graph.py
            ;;
      31)
            echo "Starting C++ and small graph"
            cd C++
            g++ large_graph.cpp utils.cpp -I boost -o main
            ./main
            ;;
      32)
            echo "Starting C++ and Medium graph"
            cd C++
            g++ large_graph.cpp utils.cpp -I boost -o main
            ./main
            ;;
      33)
            echo "Starting C++ and Large graph"
            cd C++
            g++ large_graph.cpp utils.cpp -I boost -o main
            ./main
            ;;
      *)
            echo "An error occurred"
            ;;
esac
