#!/bin/bash

clear

function sanitize_input() {
      if [ $1 -eq $1 2>/dev/null ] && [ $1 -gt 0 ] && [ $1 -lt 4 ]
      then
            return 0
      else
            return 1
      fi
}

echo "Select a technology to test with"
echo "1. Java"
echo "2. Python"
echo "3. C++"
read technology
sanitize_input $technology

while [ $? -eq 1 ]
do
      echo "Please enter a number between 1 and 3"
      read technology
      sanitize_input $technology
done

echo "Select the size of graph to use for the tests"
echo "1. Small (100 nodes)"
echo "2. Medium (1,000 nodes)"
echo "3. Large (10,000 nodes)"
read graph
sanitize_input $graph

while [ $? -eq 1 ]
do
      echo "Please enter a number between 1 and 3"
      read graph
      sanitize_input $graph
done

case $technology$graph in
      11)
            echo "Java and small graph"
            cd Java
            javac main.java
            java main
            ;;
      12)
            echo "Java and Medium graph"
            ;;
      13)
            echo "Java and Large graph"
            ;;
      21)
            echo "Python and small graph"
            python3 Python/small_graph.py
            ;;
      22)
            echo "Python and Medium graph"
            python3 Python/medium_graph.py
            ;;
      23)
            echo "Python and Large graph"
            python3 Python/large_graph.py
            ;;
      31)
            echo "C++ and small graph"
            cd C++
            g++ main.cpp -o main
            ./main
            ;;
      32)
            echo "C++ and Medium graph"
            ;;
      33)
            echo "C++ and Large graph"
            ;;
      *)
            echo "An error occurred"
            ;;
esac
